# Generated by Django 5.2.7 on 2025-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_type', models.CharField(max_length=50)),
                ('ppg', models.CharField(max_length=50)),
                ('pack_size', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('date', models.DateField()),
                ('brcatid', models.IntegerField()),
                ('sales_value', models.FloatField()),
                ('volume', models.FloatField()),
                ('volume_units', models.FloatField()),
                ('d1', models.FloatField(blank=True, null=True)),
                ('d2', models.FloatField(blank=True, null=True)),
                ('d3', models.FloatField(blank=True, null=True)),
                ('d4', models.FloatField(blank=True, null=True)),
                ('d5', models.FloatField(blank=True, null=True)),
                ('d6', models.FloatField(blank=True, null=True)),
                ('av1', models.FloatField(blank=True, null=True)),
                ('av2', models.FloatField(blank=True, null=True)),
                ('av3', models.FloatField(blank=True, null=True)),
                ('av4', models.FloatField(blank=True, null=True)),
                ('av5', models.FloatField(blank=True, null=True)),
                ('av6', models.FloatField(blank=True, null=True)),
                ('ev1', models.FloatField(blank=True, null=True)),
                ('ev2', models.FloatField(blank=True, null=True)),
                ('ev3', models.FloatField(blank=True, null=True)),
                ('ev4', models.FloatField(blank=True, null=True)),
                ('ev5', models.FloatField(blank=True, null=True)),
                ('ev6', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
