# Generated by Django 5.2.7 on 2025-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='brcatid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
