# Generated by Django 5.2.7 on 2025-10-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0003_remove_salesdata_av1_remove_salesdata_av2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='date',
        ),
    ]
