# Generated by Django 5.2.7 on 2025-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0004_remove_salesdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='pack_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='pack_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='ppg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
