# Generated by Django 5.2.7 on 2025-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0005_alter_salesdata_pack_size_alter_salesdata_pack_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='ppg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
