# Generated by Django 5.2.7 on 2025-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0006_alter_salesdata_ppg'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='AV1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='AV2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='AV3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='AV4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='AV5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='AV6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='D6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='EV6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='brcat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sales_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='volume_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='market',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
